services: 
    gateway:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: gateway
        ports:
            - "8000:8000"
        volumes:
            - ./gateway:/var/www/html
        working_dir: /var/www/html/
        tty: true
        stdin_open: true
        networks:
            red_publica:
                ipv4_address: 192.168.40.2
    transacciones:
        build: 
            context: .
            dockerfile: Dockerfile
        container_name: transacciones
        ports:
            - "8001:8000"
        volumes:
            - ./transacciones:/var/www/html
        working_dir: /var/www/html
        tty: true
        stdin_open: true
        networks:
            red_publica:
                ipv4_address: 192.168.40.3
    notificaciones:
      build: 
          context: .
          dockerfile: Dockerfile
      container_name: notificaciones
      ports:
          - "8002:8000"
      volumes:
          - ./notificaciones:/var/www/html
      working_dir: /var/www/html
      tty: true
      stdin_open: true
      networks:
        red_publica:
            ipv4_address: 192.168.40.4
        
    db:
        image: mysql:8.0
        container_name: mysql_db
        ports:
         - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            red_publica:
                ipv4_address: 192.168.40.5

    api_flask:
      image: python:3.12.10
      container_name: api_flask
      ports:
          - "5000:5000"
      networks:
        red_publica:
          ipv4_address: 192.168.40.6
      

networks:
  red_publica:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24
volumes:
    dbdata:

