FROM jenkins/jenkins:lts

# Cambiar a usuario root para instalar Docker
USER root

# Instalar Docker CLI
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg \
    lsb-release && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null && \
    apt-get update && \
    apt-get install -y docker-ce-cli && \
    rm -rf /var/lib/apt/lists/*
# Instalar PHP y extensiones
RUN apt-get update && apt-get install -y \
    php php-cli php-mbstring php-xml php-curl unzip curl git

# Instalar Composer
RUN curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer

# Instalar Docker Compose
RUN curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose && \
    chmod +x /usr/local/bin/docker-compose && \
    ln -s /usr/local/bin/docker-compose /usr/bin/docker-compose

# Agregar el usuario jenkins al grupo docker
RUN groupadd -g 999 docker || true && \
    usermod -aG docker jenkins


# Volver al usuario jenkins
USER jenkins

# Configurar Jenkins para ejecutarse en modo daemon
#ENV JAVA_OPTS -Djenkins.install.runSetupWizard=false

# Exponer puertos
EXPOSE 8080 50000
